# Ejercicio 1

In [1]:
# Crea un array de enteros 4X2 e imprime sus
# atributos. Nota: El elemento debe ser de tipo
# unsignedint16. Imprime los siguientes atributos:
# La shape del array.
# Las dimensiones del array.
# El tamaño de cada elemento del array en bytes.

import numpy as np

# array = np.empty((4, 2), dtype=np.uint16)

array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)
print("Shape del array:", array.shape)
print("Dimensiones del array:", array.ndim)
print("Tamaño de cada elemento en bytes:", array.itemsize)


array_2 = np.random.randint(0, 20, size=(4, 2), dtype=np.uint16)

print(array_2)
print("Shape del array:", array_2.shape)
print("Dimensiones del array:", array_2.ndim)
print("Tamaño de cada elemento en bytes:", array_2.itemsize)

Shape del array: (4, 2)
Dimensiones del array: 2
Tamaño de cada elemento en bytes: 2
[[16 19]
 [10 11]
 [19  6]
 [ 4  9]]
Shape del array: (4, 2)
Dimensiones del array: 2
Tamaño de cada elemento en bytes: 2


# Ejercicio 2

In [2]:
# Crea una matriz de enteros 5X2 de un rango
# entre 100 y 200 tal que la diferencia entre cada
# elemento sea 10

import numpy as np

matrix = np.arange(100, 200, 10).reshape(5, 2)

print(matrix)


[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


## Ejercicio 3

In [3]:
# A continuación se muestra el array Numpy
# proporcionado. Devuelve un array de elementos
# tomando la tercera columna de todas las filas.


import numpy as np
sampleArray = np.array([[11,22, 33], 
                        [44, 55, 66], 
                        [77, 88, 99]])

tercera_columna = sampleArray[:, 2]
print(tercera_columna)

[33 66 99]


## Ejercicio 4

In [4]:
# Devuelve un array de filas impares y columnas
# pares dado el siguiente array:

import numpy as np
sampleArray = np.array([[ 3,  6,  9, 12], 
                        [15, 18, 21, 24], 
                        [27, 30, 33, 36], 
                        [39, 42, 45, 48], 
                        [51, 54, 57, 60]])

# es decir que tengo que tomar los valores de las columnas pares y las filas impares, donde tanto las filas como las columnas empiezan en 0
# de las filas tengo que tomar las filas 1 y 3 y de las columnas el 0 y 2

resultado = sampleArray[1::2, ::2] #empiezo en la fila 1 y avanzo de 2 en dos (1::2) y las columnas empiezo por la columna 0 y salto de 2 en 2 igual(::2)
print(resultado)

[[15 21]
 [39 45]]


## Ejercicio 5

In [5]:
# Crea una matriz de resultados sumando las
# siguientes dos matrices de NumPy. А
# continuación, modifica la matriz de resultados
# calculando el cuadrado de cada elemento.

import numpy as np

arrayone = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4,7, 1]])

result = arrayone + arrayTwo
result = np.square(result)

print(result)

[[ 400 1521 1089]
 [ 625  625  784]]


## Ejercicio 6

In [6]:
# Divide la matriz en cuatro submatrices de igual
# tamaño. Nota: Crea una matriz de enteros 8x3
# de un rango entre 10 y 34 de tal manera que la
# diferencia entre cada elemento sea 1 y luego
# divide la matriz en cuatro submatrices de igual
# tamaño

import numpy as np

# Crea una matriz de enteros 8x3 de un rango entre 10 y 34
matrix = np.arange(10, 34).reshape(8, 3)

# Divide la matriz en cuatro submatrices de igual tamaño
submatrices = np.split(matrix, 4, axis=0)

print("Submatriz 1:")
print(submatrices[0])
print("\nSubmatriz 2:")
print(submatrices[1])
print("\nSubmatriz 3:")
print(submatrices[2])
print("\nSubmatriz 4:")
print(submatrices[3])

Submatriz 1:
[[10 11 12]
 [13 14 15]]

Submatriz 2:
[[16 17 18]
 [19 20 21]]

Submatriz 3:
[[22 23 24]
 [25 26 27]]

Submatriz 4:
[[28 29 30]
 [31 32 33]]


## Ejercicio 7

In [7]:
# Ordena el siguiente array de NumPy:
# Caso 1: Ordenar el array por la segunda fila
# Caso 2: Ordenar el array por la segunda columna


import numpy as np

sampleArray = np.array([[34,43,73], 
                        [82,22,12], 
                        [53,94,66]])

# argsort devuelve los índices ordenados
# Ordenar por la segunda fila
orden = np.argsort(sampleArray[1])
# ya en orden tenemos las filas ordenadas
resultado1 = sampleArray[:, orden]

print("Array ordenado por la segunda fila:")
print(resultado1)


# Ordenar por la segunda columna 
orden = np.argsort(sampleArray[:, 1])
resultado2 = sampleArray[orden, :]

print("Array ordenado por la segunda columna:")
print(resultado2)

Array ordenado por la segunda fila:
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Array ordenado por la segunda columna:
[[82 22 12]
 [34 43 73]
 [53 94 66]]


## Ejercicio 8

In [8]:
# Imprime el máximo del eje 0 y el mínimo del eje 1
# de la siguiente matriz bidimensional:

import numpy as np
sampleArray = np.array([[34,43,73],
                        [82,22,12], 
                        [53,94,66]])

max_eje0 = np.max(sampleArray, axis=0)
min_eje1 = np.min(sampleArray, axis=1)

print("Máximo del eje 0:")
print(max_eje0)

print("Mínimo del eje 1:")
print(min_eje1)



Máximo del eje 0:
[82 94 73]
Mínimo del eje 1:
[34 12 53]


## Ejercicio 9

In [9]:
# Elimina la segunda columna de una matriz dada е
# inserta la siguiente columna nueva en su lugar.

import numpy as np
sampleArray = np.array([[34,43,73], 
                        [82,22,12], 
                        [53,94,66]])

newColumn = np.array([[10,10,10]])

sampleArray = np.delete(sampleArray, 1, axis=1)
sampleArray = np.insert(sampleArray, 1, newColumn, axis=1)  

print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]
